Arcanization
gfx-rs/gfx-rs.github.io pull request #49
Opened 2023-11-24 08:56 UTC by nical

2023-11-24 19:39 UTC, cwfitzgerald requested changes

2023-11-24 19:39 UTC, cwfitzgerald commented on _posts/2023-11-24-arcanization.md
> +If you have used `wgpu`, there is decent chance that you have had to work around the restrictions imposed by the `'rpass` lifetime in a lot of `RenderPass`'s methods, such as `set_bind_group`, `set_p
We shouldn't mention this PR, it doesn't actually fix the problem, just removes the lifetimes.

2023-11-24 20:20 UTC, cwfitzgerald approved these changes
Nice!

2023-11-24 20:20 UTC, merged

2023-11-24 20:47 UTC, a1phyr commented
Hi ! Thanks for this blog post !

The images links are though.

2023-11-25 00:32 UTC, cwfitzgerald commented
They should be fixed now